function plot_dialog
tmp_path = strsplit(matlab.desktop.editor.getActiveFilename, filesep);
cd(fullfile(tmp_path{1:end-1}));
d = dialog('Position',[800 500 300 100],'Name','Choose to plot');


btn1 = uicontrol('Parent',d,...
    'Position',[50 45 70 25],...
    'String','Continue',...
    'FontSize',10,...
    'Callback',['delete(gcf);ROI_time = str2num(cell2mat(inputdlg(''Please enter the time window of interest (second)(e.g. 0.2 0.3):'')));',...
    'PlotCond = questdlg(''Would you like to plot results of all conditions?'',''Please choose'',''Yes'',''Specific condition'',''Yes'');',...
    'if strcmp(PlotCond,''Yes'');all_cond = 1;spec_cond=0;elseif strcmp(PlotCond,''Specific condition'');all_cond = 0;spec_cond = str2num(cell2mat(inputdlg(''Please enter the order of interested conditions (e.g. 1 2):'')));end;',...
    'if all(all_cond==0 & strcmp(strsplit(num2str(spec_cond)),''0''))==1;spec_cond = str2num(cell2mat(inputdlg(''Please enter the interested conditions but not the 0 (e.g. 1 2):'')));end;',...
    'ifsave1 = questdlg(''Would you like save the figure(s) automatically?'',''Please choose'',''Yes'',''No'',''Yes'');if strcmp(ifsave1,''Yes'');isave = 1;else;isave = 0;end;',...
    'mne_visualization(icond,isave,all_cond,spec_cond, time_range, channel_num, data_path, eeglab_path, erp_cond, fieldtrip_path, output_path, grid_resolution, ROI_time);']);

btn2 = uicontrol('Parent',d,...
    'Position',[200 45 70 25],...
    'String','Quit',...
    'FontSize',10,...
    'Callback','delete(gcf)');

uiwait(d)
end