function plot_dialog
tmp_path = strsplit(matlab.desktop.editor.getActiveFilename, filesep);
cd(fullfile(tmp_path{1:end-1}));
d = dialog('Position',[800 500 300 100],'Name','请选择是否画图？');


btn1 = uicontrol('Parent',d,...
    'Position',[50 45 70 25],...
    'String','继续',...
    'FontSize',10,...
    'Callback',['delete(gcf);ROI_time = str2num(cell2mat(inputdlg(''请输入感兴趣的ERP时间窗范围(秒)(如:0.2 0.3)：'')));',...
    'PlotCond = questdlg(''是否画出所有条件的溯源图？'',''请选择'',''Yes'',''Specific condition'',''Yes'');',...
    'if strcmp(PlotCond,''Yes'');all_cond = 1;spec_cond=0;elseif strcmp(PlotCond,''Specific condition'');all_cond = 0;spec_cond = str2num(cell2mat(inputdlg(''请输入感兴趣的条件的顺序(是顺序，而不是条件名称，如:1 2)：'')));end;',...
    'if all(all_cond==0 & strcmp(strsplit(num2str(spec_cond)),''0''))==1;spec_cond = str2num(cell2mat(inputdlg(''请输入0以外的感兴趣的条件(如:1 2)：'')));end;',...
    'ifsave1 = questdlg(''是否自动保存溯源图？'',''请选择'',''Yes'',''No'',''Yes'');if strcmp(ifsave1,''Yes'');isave = 1;else;isave = 0;end;',...
    'mne_visualization(icond,isave,all_cond,spec_cond, time_range, channel_num, data_path, eeglab_path, erp_cond, fieldtrip_path, output_path, grid_resolution, ROI_time);']);

btn2 = uicontrol('Parent',d,...
    'Position',[200 45 70 25],...
    'String','退出',...
    'FontSize',10,...
    'Callback','delete(gcf)');

uiwait(d)
end